C99
codeplea/tinyexpr pull request #47
Opened 2018-10-26 16:14 UTC by ccoustet

Should build using a c99 compiler. Tested on gcc 7 and MSVC 2017.

2018-10-26 17:57 UTC, codeplea commented
Thanks! This will take me some time to review though.

2025-05-05 15:05 UTC, SollyBunny requested changes

2025-05-05 15:05 UTC, SollyBunny commented on tinyexpr.h
> +union fun {
Should be `te_fun`

2025-05-05 15:05 UTC, SollyBunny commented on tinyexpr.h
> +union value {
should be `typedef union te_value { ... } te_value`

2025-05-05 15:12 UTC, SollyBunny commented
Mostly merged in [my fork](https://github.com/sollybunny/tinyexpr)

2025-05-05 16:10 UTC, SollyBunny commented
Changes in the last 2 commits should be squashed

The penultimate commit also fails the tests (the issue was the added new_expr functions)

2026-08-05 04:03 UTC, codeplea commented
Closing — master has since picked up the pieces of this that fit (executable bit, warning fixes, ARMCC support in 40fad97), and CMake support is out of scope for this repository. Thank you.

2026-08-05 04:03 UTC, closed without merging